src/makefile
src/test/kmailbox.c
src/test/kportal.c
src/test/ksync.c
src/test/kthread.c
src/test/perf.c
src/test/signal.c
src/test/sleep.c

In this PR, I remove `clean-kernel` label from makefile because it belongs to the microkernel level.
I also add `\n` to prints on tests.

Makefile error and Missing New Line on Prints

---

include/nanvix/sys/noc.h
src/libnanvix/ikc/noc.c
src/test/kmailbox.c
src/test/knoc.c
src/test/kportal.c
src/test/ksync.c
src/test/main.c
src/test/test.h

In this PR, I add kernel calls to get/set node numbers and the related tests.
I also update the old calls in other parts of the code.
Related Issues
--------------------
- [[test] Unit Tests for NoC Kernel Calls](https://github.com/nanvix/libnanvix/issues/2)

[ikc] Kernel Call to Get/Set NoC Node Numbers

---

src/test/kmailbox.c
src/test/knoc.c
src/test/kportal.c
src/test/ksync.c
src/test/kthread.c
src/test/perf.c
src/test/signal.c
src/test/sleep.c

In this PR, tests to evaluate virtual to hardware synchronization points multiplexation were added. Namely:
- `test_api_sync_multiple_create_open()`: tests if it's possible to call `do_vsync_create` and `do_vsync_open` multiple times, limited only by `KSYNC_MAX`;

[test] Unit tests for Sync Multiplex

---

include/nanvix/sys/mailbox.h
src/libnanvix/ikc/mailbox.c
src/libnanvix/ikc/stdmailbox.c
src/test/kmailbox.c

In this PR the regression tests were updated to get inline with the new Mailbox Interface that supports messages multiplexing on the kernel. Also, the tests set were enhanced to evaluate a greater range of behaviors.
- `test_api_mailbox_multiple_create_open` -> `test_api_mailbox_virtualization`
- `test_api_mailbox_multiplex` -> `test_api_mailbox_multiplexation`
- `test_fault_mailbox_bad_ioctl` -> `test_fault_mailbox_bad_mbxid`
- **`test_api_mailbox_multiplexation_2`**: to test out of order reception;
- **`test_api_mailbox_multiplexation_3`**: to test multiplexed messages storage;
- **`test_api_mailbox_pending_msg_unlink`**: to assert that the kernel avoids `mailbox_unlink` calls on ports that have pending messages;
- `test_fault_mailbox_double_create`
- `test_fault_mailbox_bad_unlink`
- …

[test] KMailbox Multiplexation Tests

---

src/libnanvix/ikc/portal.c
src/test/kmailbox.c
src/test/kportal.c
src/test/ksync.c

In this PR, we added more API tests to evaluate the messages forwarding implementation in the kernel. It were added tests for Mailbox and Portal, namely:
- `test_api_mailbox_msg_forwarding`
- `test_api_portal_msg_forwarding`
Also, small corrections were made on the existing ones to remove faulting tests on behaviors that are allowed.

[tests] Messages Forwarding Tests

---

src/libnanvix/ikc/mailbox.c

In this PR, we retry a read when it returns `ENOMSG` error.

[ikc] Mailbox Non-blocking Read

---

src/test/kmailbox.c

This PR corrects the Bad Mbxid test for Kmailbox, updating it to be in accord with the new dynamic alloc implemented in Microkernel.

[tests] Bugfix: Kmailbox Bad Mbxid

---

include/nanvix/sys/noc.h
src/libnanvix/ikc/noc.c
src/test/kportal.c

This PR defines the support to the `communicator_get_port` kernel call, attending the necessity of knowing which port a `portal_open` call allocated.

[ikc] New Communicator Get_Port Kcall

---

src/test/ikc.c
src/test/kmailbox.c
src/test/kportal.c
src/test/test.h

In this PR, some common constants defined in the multiple IKC test files were generalized and put into `test.h`, to padronize tests executions. Now, all important parameters of execution for these tests are on the same file, permitting to apply them to all over tests on a single execution.

[tests] IKC Common Constants

---

src/libnanvix/ikc/portal.c
src/test/kportal.c
src/test/test.h

In this PR, I introduce user-side features to support the communication of arbitrary sizes through the portal.
I made only available on synchronous communication because is difficult to support it on asynchronous on account of the current behavior. For instance, when a wait function returns with `1`, we must try again a aread/awrite because the portal system didn't receive the right message. At this point, I suppose that we must change the return value for `-EAGAIN` to be more expressive.
[[ikc] Supoprt for Arbitrarly Large Portal Transfers](https://github.com/nanvix/libnanvix/issues/26)
[Enhancement: Ordered and auxiliary mbuffer pool. (Microkernel PR)](https://github.com/nanvix/microkernel/pull/247)

[ikc] Breaking Large Transfers Using Portals

---

include/nanvix/runtime/barrier.h
include/nanvix/runtime/stdikc.h
src/libnanvix/ikc/barrier.c
src/libnanvix/ikc/stdsync.c

In this pull request I introduce a generic barrier implementation on top of `ksync`. Furthermore I have changed the implementation of our `stdsync` to use this barrier primitive as backend.
- Closes https://github.com/nanvix/libnanvix/issues/33

[ikc] Generic Barrier

---

src/test/kthread.c
src/test/test.h

In this PR, I fix a function name and enable stress tests of the kthread system.
- Closes https://github.com/nanvix/libnanvix/issues/36
[[tm] Bugfix: Stress tests unable to create kernel threads](https://github.com/nanvix/microkernel/pull/253)

[test]  Enable Stress Tests in Thread System

---

include/nanvix/sys/mailbox.h
include/nanvix/sys/noc.h
include/nanvix/sys/portal.h
include/nanvix/sys/sync.h
makefile
src/libnanvix/ikc/mailbox.c
src/libnanvix/ikc/mportal.c
src/libnanvix/ikc/msync.c
src/libnanvix/ikc/noc.c
src/libnanvix/ikc/portal.c
src/libnanvix/ikc/sync.c
src/test/kmailbox.c
src/test/kportal.c
src/test/main.c
src/test/test.h

In this PR, I introduce the implementations of Sync and Portal using mailboxes to perform the expected behavior.
By setting CFLAG `__NANVIX_IKC_USES_ONLY_MAILBOX ` to 1, you are enabling the use of this implementation. Otherwise, the default implementation will be used.
Multiplexing tests were also added with sizes larger than the buffers used.
[[ikc] Enhancement: IKC support to allow communication only in mailboxes](https://github.com/nanvix/microkernel/pull/256)

[ikc] Sync and Portal Using Mailboxes

---

src/libnanvix/ikc/mailbox.c
src/libnanvix/ikc/mportal.c
src/libnanvix/ikc/msync.c

In this PR, I fix some weird behaviors of Portal on ONLY_MAILBOX mode. But that solution does not support `IKC thread multiplexing ping-pong reverse` test. The limitation is specified by #49.
[[ikc] Current ONLY_MAILBOX mode does not support IKC thread multiplexing ping-pong reverse test #49](https://github.com/nanvix/libnanvix/issues/49)

[ikc] Limited but stable version of the Portal on Mailbox

---

include/nanvix/sys/mailbox.h
src/libnanvix/ikc/mailbox.c

In this PR, we add to the IKC Mailbox interface the ```kmailbox_set_remote``` function, to be used instead of ```kmailbox_ioctl``` with the correct IOCTL opcode.
This modification comes to facilitate the operation usage and to keep the coding style clean when performing this functionality in the above layers.

[ikc] Feature: Mailbox Set Remote

---

include/nanvix/runtime/fence.h
src/libnanvix/thread/fence.c
src/test/ikc.c
src/test/kmailbox.c
src/test/kportal.c

In this PR, we moved the Threads ```Fence``` implementation from the Libnanvix test files to an individual header file and its related implementation, this way, enabling this implementation to be exported and used in the above layers. 
- Closes #70 - [[pm] Export User Threads Fence to the above layers](https://github.com/nanvix/libnanvix/issues/70)
For now, this Fence is implemented using raw Spinlocks. One possibility of improvement is to implement this abstraction using Semaphores or Mutexes, which would result in better efficiency since threads waiting may sleep, instead of occupying the processor with busy waiting.

[pm] Threads Fence

---

include/nanvix/sys/condvar.h
src/libnanvix/thread/condvar.c

In this PR, we guarantee that the `condvar` abstraction keeps the releasing order when releasing threads that were waiting in a synchronization point. 
Closes #75

[pm] Synchronization Condvar Release Ordering in All Platforms

---

include/nanvix/sys/mailbox.h
include/nanvix/sys/portal.h
src/libnanvix/ikc/mailbox.c
src/libnanvix/ikc/portal.c
src/libnanvix/ikc/stdmailbox.c
src/libnanvix/ikc/stdportal.c

In this PR, we made the function ```get_port``` available for both Portal and Mailbox interfaces, in order to permit a service to retrieve the underlying port of a communicator. Additionally, we corrected the ```std_get_port``` routines when using the Standard IKC structures, which were inconsistent with the new thread system implemented in the underlying levels.

[ikc][bugfix] Communicators Get_Port

---

include/nanvix/sys/condvar.h
src/libnanvix/thread/condvar.c

In this PR, we implemented the ```Condvar_Broadcast``` function, in order to permit for a thread to wake up all threads waiting in a single Condition Variable. For this, we reutilized the Condvar_Signal implementation to wake up threads while the head of the sleeping threads is not empty.
- Closes #81 - [[pm][thread] Condvar Broadcast](https://github.com/nanvix/libnanvix/issues/81)

[pm][thread] Condvar Broadcast

---

include/nanvix/sys/condvar.h
include/nanvix/sys/mutex.h
include/nanvix/sys/semaphore.h
src/libnanvix/thread/condvar.c
src/libnanvix/thread/mutex.c
src/libnanvix/thread/semaphore.c
src/test/condvar.c
src/test/main.c
src/test/mutex.c
src/test/semaphore.c

In this PR, I change the responsibility of how the mutex/semaphore/condvar deals with the sleep/wakeup calls.
This change is needed because the previous one can introduce deadlocks/livelocks on incoming submodules changes.

[thread] Sleep/wakeup Scheme on Mutex/Semaphore/Condvar

---

include/nanvix/runtime/fence.h
include/nanvix/runtime/stdikc.h
include/nanvix/sys/condvar.h
include/nanvix/sys/mutex.h
include/nanvix/sys/semaphore.h
include/nanvix/sys/thread.h
src/libnanvix/ikc/stdmailbox.c
src/libnanvix/ikc/stdportal.c
src/libnanvix/ikc/stdsync.c
src/libnanvix/thread/condvar.c
src/libnanvix/thread/fence.c
src/libnanvix/thread/mutex.c
src/libnanvix/thread/semaphore.c
src/libnanvix/thread/thread.c
src/test/barrier.c
src/test/condvar.c
src/test/fence.c
src/test/ikc.c
src/test/kmailbox.c
src/test/kportal.c
src/test/ksync.c
src/test/kthread.c
src/test/main.c
src/test/mutex.c
src/test/semaphore.c
src/test/sleep.c
src/test/test.h

In this PR, I introduce tests to evaluate and stimulate preemptive threads through scheduling and affinities with the nuclei.
In addition, we correct some performance bugs of synchronization abtractions between threads and their interfaces.
Finally, pack problems with thread mapping for ports in IKC standards.
[[pm][ikc] Feature: Preemptive threads](https://github.com/nanvix/microkernel/pull/298)

[pm][ikc] Feature: preemptive threads
