src/libnanvix/ikc/portal.c, src/libnanvix/ikc/sync.c, src/test/kmailbox.c, src/test/knoc.c, src/test/kportal.c, src/test/ksync.c, src/test/main.c
In this PR, I refactor and fix some bugs on IKC code and tests.
=> IKC Kernel Calls and Tests

build/makefile.contrib, include/nanvix/sys/mailbox.h, include/nanvix/sys/portal.h, include/nanvix/sys/sync.h, src/libnanvix/ikc/mailbox.c, src/libnanvix/ikc/noc.c, src/libnanvix/ikc/portal.c, src/libnanvix/ikc/sync.c, src/test/kmailbox.c, src/test/kportal.c, src/test/ksync.c
In this PR, I introduce kernel calls to IO Control Operations and related tests.
=> Feature: Kernel Calls for IO Control Operations

src/test/kmailbox.c
In this PR, tests to evaluate virtual to hardware mailboxes multiplexation were added. Namely:
- `test_api_mailbox_multiple_create_open()`: tests if it's possible to call `do_vmailbox_create` and `do_vmailbox_open` multiple times, limited only by `KMAILBOX_MAX`;
- `test_api_mailbox_multiplexation()`: tests if the virtual mailboxes are being correctly multiplexed to their respective hardware mailboxes when transfering data.
=> [test] Unit tests for Mailbox Multiplex

src/test/kportal.c
In this PR, tests to evaluate virtual to hardware portals multiplexing were added. Namely:
- `test_api_portal_multiple_create_open()`: tests if it's possible to call `do_vportal_create` and `do_vportal_open` multiple times, limited only by `KPORTAL_MAX`;
- `test_api_portal_multiplex()`: tests if the virtual portals are being correctly multiplexed to their respective hardware portals when transferring data;
- `test_api_portal_allow()`: tests if a read occurs only after an allow for a given vportal, if allows are correctly revoked after reads and if HW portal allows are considered when allowing vportals that map to these fd's.
Also, tests to evaluate portal faults were added. Namely:
- `test_fault_portal_bad_unlink()`: tries to unlink an output vportal;
- `test_fault_portal_double_close()`: …
=> [test] Unit tests for Portal Multiplex

src/test/kportal.c
In this PR the Kportal regression tests were updated to get inline with the kernel multiplexation and enhanced to evaluate a greater range of behaviors.
- **`test_api_portal_multiplexation_3`**: to assert correct messages selection on multiplexed `portal_aread`;
- **`test_api_portal_multiplexation_4`**: to assert the correct multiplexed messages storage;
- **`test_api_portal_pending_msg_unlink`**: to assert that the kernel avoids `portal_unlink` calls on ports that have pending messages;
- `test_fault_portal_double_create`
- `test_fault_portal_invalid_allow`
- `test_fault_portal_bad_read`
- `test_fault_portal_invalid_write_size`
- `test_fault_portal_null_write`
- `test_fault_portal_bad_portalid`
=> [test] KPortal Multiplexation Tests

src/test/kmailbox.c, src/test/kportal.c
In this PR, the IKC regression tests were updated to get inline with the kernel IKC initialization functions, removing dummy initializations and updating tests constants.
=> [tests] Enhancement: IKC Initialization

src/test/ikc.c, src/test/kmailbox.c, src/test/kportal.c
In this PR, I introduce stressful tests of mailbox, portal, and mailbox+portal for inter-cluster communication.
=> [test] Feature: Stressful tests of local communication

build/unix64/make/makefile.cflags
In this PR, I select CFLAGS manually because -O3 is breaking the execution on Unix.
=> [unix] Bugfix: Insecure optimizations

src/test/barrier.c, src/test/ikc.c, src/test/kmailbox.c, src/test/kportal.c, src/test/main.c, src/test/test.h
In this PR, I add barriers before each intercluster communication test to avoid interferences.
=> [test] Use Barriers in Tests

src/libnanvix/ikc/stdsync.c, src/libnanvix/ikc/sync.c
In this PR, I change the user-side of the sync system to use the new interface and behavior. I correct check if sync occurred on `stdsync_fence`
[Enhancement: Sync system refactor (Microkernel PR)](https://github.com/nanvix/microkernel/pull/248)
=> Enhancement: Sync system refactor

.travis.yml, src/libnanvix/ikc/portal.c, src/test/main.c, src/test/test.h
In this PR, I fix the data size of the portal messages.
[[ikc] Bugfix: Message sizes](https://github.com/nanvix/microkernel/pull/251)
=> [ikc] Wrong Data Size of the Portal

include/nanvix/sys/sync.h, src/libnanvix/ikc/mailbox.c, src/libnanvix/ikc/mportal.c, src/libnanvix/ikc/msync.c, src/libnanvix/ikc/sync.c, src/test/kmailbox.c, src/test/kportal.c, src/test/ksync.c
In this PR, I add the IOCTL interface to the Sync module and expand IOCTL operations.
[[ikc] Enhancement: Sync's IOCTL and Operation Counters in IOCTL](https://github.com/nanvix/microkernel/pull/258)
=> [ikc] Sync's IOCTL and Operation Counters in IOCTL

src/libnanvix/ikc/msync.c
In this PR, I introduce counters to the sync table to keep the number of signals a sync point received from a cluster. This avoids dropping signals.
[[ikc] Unnecessary dropping of signals in the Sync module (Mailbox Implementation) #40](https://github.com/nanvix/libnanvix/issues/40)
[Enhancement: Update HAL](https://github.com/nanvix/microkernel/pull/259)
=> [ikc] Don't Drop Signals in the Sync Module (Mailbox Implementation) 

include/nanvix/runtime/barrier.h
This PR makes a small correction on `BARRIER_IS_VALID` macro.
=> [bugfix] BARRIER_IS_VALID Macro Correction

src/libnanvix/ikc/mportal.c
In this PR, I assign the latency of the communication through a portal over mailboxes to the buffer eliminating interference between ports and eliminate the cumulative sum of microkernel latency.
[[ikc] Bugfix: Interference on latency between differents ports](https://github.com/nanvix/microkernel/pull/265)
=> [ikc] Interference between ports and cumulative latency measures

src/test/kmailbox.c
In this PR we included in the regression tests set a simple routine to ensure the correctness of the implementation when specifying the remote source using IOCTL in the Mailbox abstraction. The routine is `test_stress_mailbox_thread_specified_source()`, and it consists in a master thread specifiyng some of the messages that it wants to read from multiple writes that are made concurrently by multiple slave threads, and in a second moment reading the remaining ones in any order in the normal way, to ensure that the remote address reset is really working.
=> [test] Mailbox Specified Source

include/nanvix/sys/mutex.h, src/libnanvix/thread/mutex.c, src/test/condvar.c, src/test/main.c, src/test/mutex.c, src/test/sleep.c, src/test/test.h
Extended mutex functions and provided mutex type attribute
Closes #61
=> [pm] Mutex Extensions (issue #61)

include/nanvix/sys/semaphore.h, src/libnanvix/thread/semaphore.c, src/test/main.c, src/test/semaphore.c, src/test/test.h
Extended semaphore functions
Closes #62
=> [pm] Enhancement: Semaphore Extensions (issue #62)

src/test/kthread.c
In this PR I implemented three tests to check the return value of threads, theses are:
- kthread return NULL : Asserts if the thread can return NULL.
- kthread return integer : Asserts if the thread can return an integer.
- kthread return pointer : Asserts if the thread can return a pointer.
[[pm] Thread Return Value (nanvix/microkernel)](https://github.com/nanvix/microkernel/pull/288)
=> [pm] Thread return value tests

src/test/kmailbox.c
In this PR, we enhance the IKC Testing Pool by adding new fault tests related to the ```Kmailbox_set_remote``` functionality. In sum, these tests were implemented to ratify the security improvements that were made in the underlying submodules, related with this IOCTL operation.
=> [ikc][tests] Added Kmailbox_set_remote Fault Tests

include/nanvix/runtime/stdikc.h, include/nanvix/sys/excp.h, include/nanvix/sys/task.h, src/libnanvix/etc/exception.c, src/libnanvix/ikc/mailbox.c, src/libnanvix/ikc/noc.c, src/libnanvix/ikc/portal.c, src/libnanvix/ikc/stdmailbox.c, src/libnanvix/ikc/stdportal.c, src/libnanvix/ikc/stdsync.c, src/libnanvix/ikc/task.c, src/libnanvix/ikc/task.h, src/libnanvix/thread/task.c, src/test/kmailbox.c, src/test/kportal.c, src/test/ktask.c, src/test/main.c
Move dev branch to the latest dev version
=> Feature: Introduce Task Engine (disabled by default)
